<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  <Version>1.1.0</Version>
  <AssemblyVersion>1.1.0.0</AssemblyVersion>
  <FileVersion>1.1.0.0</FileVersion>
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
<ApplicationIcon>Resources\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Basic_red_dot.png" />
    <None Remove="logo.png" />
    <None Remove="noname-cutout.png" />
    <None Remove="noname.png" />
    <None Remove="nxcutout.png" />
    <None Remove="printly.png" />
    <None Remove="Resources\efficiency.ico" />
    <None Remove="Resources\logo.ico" />
    <None Remove="Resources\png\63699.png" />
    <None Remove="Resources\png\Basic_green_dot.png" />
    <None Remove="Resources\png\Basic_red_dot.png" />
    <None Remove="Resources\png\efficiency.png" />
    <None Remove="Resources\png\img1.png" />
    <None Remove="Resources\png\img2.png" />
    <None Remove="Resources\png\loading\rotating.png" />
    <None Remove="Resources\png\loading\stationary.png" />
    <None Remove="Resources\png\login-page-password.png" />
    <None Remove="Resources\png\logo.png" />
    <None Remove="Resources\png\printly.png" />
    <None Remove="Resources\png\user.png" />
    <None Remove="rotating.png" />
    <None Remove="user.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\png\nxcutout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\efficiency.ico" />
    <Resource Include="Resources\logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\63699.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\Basic_green_dot.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\Basic_red_dot.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\efficiency.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\img1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\img2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\loading\rotating.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\loading\stationary.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\login-page-password.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\printly.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\png\user.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="user.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
	  <PackageReference Include="NuGet.CommandLine" Version="6.14.0" PrivateAssets="all" ExcludeAssets="runtime;compile" />
	  <PackageReference Include="squirrel.windows" Version="1.9.0" PrivateAssets="all" ExcludeAssets="runtime;compile" />

  </ItemGroup>
	
	<PropertyGroup>
		<NugetTools>$(PkgNuGet_CommandLine)\tools</NugetTools>
		<SquirrelTools>$(Pkgsquirrel_windows)\tools</SquirrelTools>

		<Version>1.1.0</Version>

		<NuspecFile>$(SolutionDir)Printly\Printly.nuspec</NuspecFile>
	</PropertyGroup>

	<Target Name="GenerateRelease" AfterTargets="AfterBuild" Condition="$(Configuration) == Release">
		<XmlPeek XmlInputPath="$(NuspecFile)" Query="/package/metadata/id/text()">
			<Output TaskParameter="Result" ItemName="ID" />
		</XmlPeek>

		<Exec Command="$(NugetTools)\NuGet.exe pack &quot;$(NuspecFile)&quot; -Version $(Version) -Properties Configuration=Release -OutputDirectory &quot;$(SolutionDir)Deployment\GeneratedNugets&quot;" />

		<Exec Command="&quot;$(SquirrelTools)\Squirrel.exe&quot; --releasify &quot;$(SolutionDir)Deployment\GeneratedNugets\Printly.1.1.0.nupkg&quot; --releaseDir=&quot;$(SolutionDir)Deployment\Releases&quot;" />

	</Target>

</Project>


