// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Printly.Models;

public partial class Order
{
    public int OrderId { get; set; }
    [Required]
    public int ClientId { get; set; }
    [Required]
    public string Article { get; set; }

    public string Defect { get; set; }

    public decimal? Price { get; set; }

    public DateTime DateReceived { get; set; }

    [Required]
    public virtual Client Client { get; set; }

    public bool IsChecked { get; set; }

    public bool IsPrinted { get; set; }
    public string Accessories { get; set; }
    public string Description { get; set; }
    public bool IsReadyForSubmission { get; set; }
    public DateTime? IsSubmissed { get; set; }
    public string Status { get; set; }
}